services:
  tankille-app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./package.json
